# -*- coding: utf-8 -*-
"""Exploratory Data Analysis (EDA) Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIq01hJ8CLL6mzD_EYjKYb8Sx9eaSBa8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("dirty_cafe_sales.csv")

print(df.head())

print(df.shape)

print(df.info())

print(df.describe())

print(df.isnull().sum())

df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)

numeric_cols = ["Quantity", "Price Per Unit", "Total Spent"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

df["Item"].fillna(df["Item"].mode()[0], inplace=True)

df["Payment Method"].fillna(
    df["Payment Method"].mode()[0],
    inplace=True
)

df["Location"].fillna(
    df["Location"].mode()[0],
    inplace=True
)

df.drop_duplicates(inplace=True)

df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"]
)

df["Month"] = df["Transaction Date"].dt.month

df["Day"] = df["Transaction Date"].dt.day_name()

plt.figure(figsize=(8,5))

sns.countplot(x="Item", data=df)

plt.title("Most Sold Items")

plt.xticks(rotation=45)

plt.show()

sales = df.groupby("Item")["Total Spent"].sum()

sales.plot(kind='bar', figsize=(8,5))

plt.title("Revenue by Item")

plt.ylabel("Revenue")

plt.show()

df["Payment Method"].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title("Payment Method Distribution")

plt.ylabel("")

plt.show()

plt.figure(figsize=(8,5))

sns.heatmap(
    df[["Quantity",
        "Price Per Unit",
        "Total Spent"]].corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

daily_sales = df.groupby(
    "Transaction Date"
)["Total Spent"].sum()

daily_sales.plot(figsize=(12,5))

plt.title("Daily Sales Trend")

plt.ylabel("Sales")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["Total Spent"])

plt.title("Outlier Detection")

plt.show()

df.to_csv(
    "cleaned_cafe_sales.csv",
    index=False
)